### ISSUE TITLE
find an error on ads2 note week4 page27

### ISSUE THREAD

**Issue by hitfzyangdianshi** [world-class/notes#16]
https://github.com/world-class/notes/blob/845f0920b9463f7517a0452ba316337913e46280/level-5/algorithms-and-data-structures-ii/student-notes/felipe-balbi/notes.pdf

2.301 The master theorem
3. f(n) > nlogb a
For this case to be applicable, there is one extra requirement to be met: 
here should be ` a·f(n/b) ≤ c·f(n)`. The author forgot `·f(n)` here.

![image](https://user-images.githubusercontent.com/10493326/162577071-97d07a97-f376-45c2-a14b-f76268027a53.png)

**Comment by sglavoie** [comment]
I suspect @felipebalbi may not have seen this issue (tagging him just in case) – and is probably busy finishing this degree and thinking about something else. Despite this little hiccup, his notes have definitely been very helpful :wink:.

**Comment by felipebalbi** [comment]
I'll have a look, thanks for reporting.

**Comment by felipebalbi** [comment]
Updated PDF pushed, please verify :-) Again, thanks for reporting @hitfzyangdianshi
